name: bubbleexpress
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  in_date_utils: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets should be placed here instead of the dependencies section.
  assets:
    - assets/google_logo.png
    - assets/default_profile_icon.png
    - assets/facebook_logo.png

  # You can add fonts here if you plan to use custom fonts.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
